### ISSUE TITLE
 Job::command(s) never process

### ISSUE THREAD

**Issue by marshmanGit** [popphp/pop-queue#1]
I cannot seem to get Job::command" to be processed.
Researching a bit and found the following:

Worker.php:201
$this->results[$nextIndex] = $this->jobs[$nextIndex]->run();

Declaration: public function run(Application $application = null)

Application will always be null.  I spent as much time as I could in hopes to resolve the issue but had move on to work related tasks.  Your expertise will be greatly appreciated and please advise if I am totally off base here.

**Comment by nicksagona** [comment]
Thanks for the heads up on this. I'll look into it and see what I can find. If you have extended code samples of what you were trying to do exactly, that might help.

**Comment by marshmanGit** [comment]
Created a simple console route 'test' that writes a one-liner to a file and successful with ./app test

// ADD A CONSOLE JOB TO QUEUE
$queue = Queue::load('csharks-queue', new File($queueDir), $this->application());
$job = Job::command('test');  
$worker = new Worker();
$worker->addJob($job);
$queue->addWorker($worker);
$queue->pushAll();

// QUEUE references and payloads are being successfully generated.

// PROCESS THE QUEUE
$queue = Queue::load('csharks-queue', new File($queueDir), $this->application());
$queue->processWorkers();

Thus far it is only the CLI "Job::command" queue that will not process likely due to the Application not being passed in Worker.php in additional to something a little deeper and that is where I was spending more time that I have at the moment to investigate.

Thanks

**Comment by nicksagona** [comment]
Ok thanks - I'll take a look at it when I have a minute.

**Comment by nicksagona** [comment]
Ok, so it looks like this is definitely a bug due to an oversight on my part. For queues that run application commands, I built in the ability to inject the application object into the queue object so the queue would be aware of the application when it need it. However, I forgot to connect those things together when the Job `run()` command was executed. I've added that in with one line of code:

https://github.com/popphp/pop-queue/blob/master/src/Processor/Worker.php#L201

Now the only other step for a user to take is to pass down the application object into the main queue object and that should wire it up and make it work.

Grab a copy of the 1.1.2 release I just pushed out and let me know if it now functions correctly for you. Thanks!

**Comment by nicksagona** [comment]
Ok closing this issue as resolved.

**Comment by marshmanGit** [comment]
My apologies as I responded to the email and not directly here.

Thank you for your efforts...and the awesome framework.  I have used many different frameworks and settled on popphp for a cleaner ( non-bloated ) option.  I also get high requests per second benchmarks.

Anyway, using the Job::command via the queue is still not working as expected.

Interesting enough I can perform: $this->application()->run(true, 'testing'); and that works just fine, which is essentially what happens down the pipe with the queue.  So I tried tracing my issue a little deeper and ended up in the AbstractController.php dispatch function.  Seems that when the queue is used to process a Job::command that it chokes as if there may be a circular reference but I have not been successful at proving this or finding the actual problem.

I certainly have other options available but I will keep watching for any updates that you are able to conclude.

Thanks again,
Marshall

**Comment by nicksagona** [comment]
Thank you for your positive feedback - much appreciated!

As far as this issue goes, I def want to try and get it straightened out. After the patch, did you inject the main application object into the main queue object? That's a required step there - the main queue object needs to be made "aware" of the main application object in order to run commands:

```php
$queue   = Queue\Queue::load('pop-queue', $adapter, $application);
```
When you opened this issue, I was able to recreate the problem that you described (the application command would never run.) After patching lines 201-202 (actually fetching the application object from the queue object and injecting it into the run command) I was able to get it to work and the registered application command ran correctly.

Just let me know - thanks.

https://github.com/popphp/pop-queue/blob/master/src/Processor/Worker.php#L201-L202

**Comment by marshmanGit** [comment]
Hi Nick,
I'm circling back around to this issue.  I further discovered that when you place a "command" into the queue that the Router.php does not execute said command and therefore causes a segment fault to occur.  It actually continues to execute the cli command that was called initially.

The fix seems to be this and without will never call $forceRoute that gets passed when using command queue items:
Router.php : line 369
//         $action       = $this->routeMatch->getAction();
           $action       = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;

I look forward to your response.
Thanks

**Comment by nicksagona** [comment]
Thanks for the input. So the "route" or "forceRoute" is different than the `action`. The "route" or "forceRoute" contains a string that is the calling request or command e.g., "/hello/world" (HTTP) or "my-command" (CLI)

Those would then map to an `action`, which is a string that defines the name of the method to be called, so "/hello/world" might map to "MyApp\Http\IndexController->index()" and "my-command" might map to "MyApp\Console\ConsoleController->myCommand()" (Or it could be a self-contained closure as well.)

Therefore the value of `$action` would be the name of the method, e.g., "index()" or "myCommand()", respectively (not the name of the calling request string)

This means your proposed solution above wouldn't work b/c if `$forceRoute` is set, it would assign the request string to the action, instead of the method that it needs to be.

I'll share below how the force route should work with the router, and how it's working on my machine. Let me know if you have some code examples to share with me of how it's not working, or how you think it should be working. If you are getting an error, perhaps it's further up the chain?

**Comment by nicksagona** [comment]
```php
// HTTP Example, index.php
class IndexController extends Pop\Controller\AbstractController
{

    public function index()
    {
        echo 'Hello World' . PHP_EOL;
    }

    public function error()
    {
        echo 'Whoops!' . PHP_EOL;
    }

}

$app = new Pop\Application([
    'routes' => [
        '/hello' => [
            'controller' => 'IndexController',
            'action'     => 'index'
        ],
        '*' => [
            'controller' => 'IndexController',
            'action'     => 'error'
        ]
    ]
]);
```

**Comment by nicksagona** [comment]
If in that file I put:
```php
$app->run();
```
and run the server on that file, and go to `http://localhost:8000/hello` the "Hello World" page will display.

If I go to `http://localhost:8000/` the "error" page will display.

If I change the line to:
```php
$app->run(true, '/hello');
```
and go to `http://localhost:8000/` the "Hello World" page will display (instead of the error page), b/c of the force route parameter being passed.

**Comment by nicksagona** [comment]
Similarly, if I do the same in a CLI app like this:
```php
// CLI example, app.php
class ConsoleController extends Pop\Controller\AbstractController
{

    public function myCommand()
    {
        echo 'Hello Console' . PHP_EOL;
    }

    public function error()
    {
        echo 'Whoops!' . PHP_EOL;
    }

}

$app = new Pop\Application([
    'routes' => [
        'my-command' => [
            'controller' => 'ConsoleController',
            'action'     => 'myCommand'
        ],
        '*' => [
            'controller' => 'ConsoleController',
            'action'     => 'error'
        ]
    ]
]);

```

**Comment by nicksagona** [comment]
Putting in the file
```php
$app->run();
```
and running `php app.php my-command` will display "Hello Console"

and running `php app.php` the "error" message will display.

If I change the line to:
```php
$app->run(true, 'my-command');
```
and run `php app.php` the "Hello Console" page will display (instead of the error message), b/c of the force route parameter being passed.

**Comment by nicksagona** [comment]
Let me know if that helps or makes sense. Thanks!

**Comment by marshmanGit** [comment]
```
Hi Nick,

First let me thank you for your time and efforts and I hope I'm not completely off track.  I feel like I follow what you are conveying but it does not seem to relate to queue processing as I am attempting.  Please see the below code sample, perhaps my issues are from not understanding how to use the queue or as you mentioned, possibly further up the chain.
--------------------------------------------------------- 

** PROPOSED CHANGE - However, I still have an issue when route and action name is different (ONLY WHEN WORKING WITH QUEUE JOBS ), otherwise this change appears to work without incident.

popphp/popphp/src/Router/Router.php
Line 369 ish:
//$action = $this->routeMatch->getAction();
$action = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;
var_dump($action);
var_dump($forceRoute);


 /*
 TEST CODE
 */
'routes'    => [
        'testTwo' => [
            'controller' => 'Csharks\Console\Controller\SampleController',
            'help'       => 'TEST 2 - call and action SAME',
            'action'     => 'testTwo'
        ],
        'testThree' => [
            'controller' => 'Csharks\Console\Controller\SampleController',
            'help'       => 'TEST 3 - call and action DIFFERENT',
            'action'     => 'testThreeDiff'
        ],
        'pushTestTwoToQueue' => [
            'controller' => 'Csharks\Console\Controller\SampleController',
            'help'       => 'Push TEST 2',
            'action'     => 'pushTestTwoToQueue'
        ],
        'pushTestThreeToQueue' => [
            'controller' => 'Csharks\Console\Controller\SampleController',
            'help'       => 'push TEST 3',
            'action'     => 'pushTestThreeToQueue'
        ],
        'processJobQueue' => [
            'controller' => 'Csharks\Console\Controller\SampleController',
            'help'       => 'Process Job Queue',
            'action'     => 'processJobQueue'
        ]
];

/*
Notice in the routes I am testing  (route & action = same name) and (route & action = different name).
Starting my test without any modifications to Router.php
*/

TEST 1:
From the cli they all can be called directly without incident and without any changes to Router.php
So we are all good at this point.

TEST 2:
./app pushTestTwoToQueue
/*
 Payload gets into the queue - so we are good here
*/

./app processJobQueue
/*
 In Router.php, $action is as expected "processJobQueue"
 $forceRoute is NULL which I would not expect
 We get a segmentation fault

 If we change Route.php
 //$action = $this->routeMatch->getAction();
 $action = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;

 And run TEST 2 again we will see that $action and $forceRoute are the same "testTwo"
 In this case we are successful
*/

*** Now revert our proposed changes to Router.php back to the original code
$action = $this->routeMatch->getAction();
// $action = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;

TEST 3:
./app pushTestThreeToQueue
/*
  Payload gets into the queue - so we are good here
*/

./app processJobQueue
/*
  Again, same result as testTwo with the segmentation fault

  Apply Router.php proposed changes
  //$action = $this->routeMatch->getAction();
  $action = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;

  Run test three again

  Queue job ends as FAIL - but no segmentation fault
  I believe the failure is because $action and $forceRoute = testThree and never route to testThreeDiff
*/

/*
  Sample controller
*/
use Pop\Queue\Adapter\File;
use Pop\Queue\Processor\Jobs\Job;
use Pop\Queue\Processor;
use Pop\Queue\Queue

class SampleController extends AbstractController
{
    public function processJobQueue()
    {
        $queue = Queue::load('csharks-queue', new File('/mnt/data/'), $this->application());
        $queue->processWorkers();
    }

    public function testTwo()
    {
        file_put_contents('/mnt/data/test2.txt', 'Hello test 2');
    }

    public function testThreeDiff()
    {
        file_put_contents('/mnt/data/test3.txt', 'Hello test 3');
    }

    public function pushTestTwoToQueue()
    {
        $queue = Queue::load('csharks-queue', new File('/mnt/data/'), $this->application());
        $job = Job::command('testTwo');
        $worker = new Processor\Worker();
        $worker->addJob($job);
        $queue->addWorker($worker);
        $queue->pushAll();
    }

    public function pushTestThreeToQueue()
    {
        $queue = Queue::load('csharks-queue', new File('/mnt/data/'), $this->application());
        $job = Job::command('testThree');
        $worker = new Processor\Worker();
        $worker->addJob($job);
        $queue->addWorker($worker);
        $queue->pushAll();
	}

}
```

**Comment by nicksagona** [comment]
Ok cool - so let me see if I can take your code examples and recreate the issue locally on my machine and hopefully we'll get to the bottom of it. I'll let you know.

**Comment by marshmanGit** [comment]
Hi Nick,  just circling back around to see if you have made any progress.
thanks

**Comment by nicksagona** [comment]
Hey - sorry, I had a really slammed January at work so I wasn't able to focus as much on Pop. But, tonight, I had some time, so I did take a look at your code sample. I got it up and running, and fortunately (or unfortunately) it's working for me w/o any issues. I did grab your code sample and dumped it into a quick and dirty `app.php` file to run and test from. Here's that code (excuse the lack of namespaces, cleanliness, etc.)

```php
#!/usr/bin/php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

class SampleController extends Pop\Controller\AbstractController
{

    protected $application = null;

    public function __construct(Pop\Application $application)
    {
        $this->application = $application;
    }

    public function testTwo()
    {
        file_put_contents(__DIR__ . '/data/test2.txt', 'Hello test 2' . PHP_EOL, FILE_APPEND);
    }

    public function testThreeDiff()
    {
        file_put_contents(__DIR__ . '/data/test3.txt', 'Hello test 3' . PHP_EOL, FILE_APPEND);
    }

    public function pushTestTwoToQueue()
    {
        $queue = Pop\Queue\Queue::load('csharks-queue', new Pop\Queue\Adapter\File(__DIR__ . '/data/'), $this->application);
        $job = Pop\Queue\Processor\Jobs\Job::command('testTwo');
        $worker = new Pop\Queue\Processor\Worker();
        $worker->addJob($job);
        $queue->addWorker($worker);
        $queue->pushAll();
    }

    public function pushTestThreeToQueue()
    {
        $queue = Pop\Queue\Queue::load('csharks-queue', new Pop\Queue\Adapter\File(__DIR__ . '/data/'), $this->application);
        $job = Pop\Queue\Processor\Jobs\Job::command('testThree');
        $worker = new Pop\Queue\Processor\Worker();
        $worker->addJob($job);
        $queue->addWorker($worker);
        $queue->pushAll();
    }

    public function processJobQueue()
    {
        echo 'Process job queue' . PHP_EOL;
        $queue = Pop\Queue\Queue::load('csharks-queue', new Pop\Queue\Adapter\File(__DIR__ . '/data/'), $this->application);
        $queue->processWorkers();
    }
}

$config = [
    'routes'    => [
        'testTwo' => [
            'controller' => 'SampleController',
            'help'       => 'TEST 2 - call and action SAME',
            'action'     => 'testTwo'
        ],
        'testThree' => [
            'controller' => 'SampleController',
            'help'       => 'TEST 3 - call and action DIFFERENT',
            'action'     => 'testThreeDiff'
        ],
        'pushTestTwoToQueue' => [
            'controller' => 'SampleController',
            'help'       => 'Push TEST 2',
            'action'     => 'pushTestTwoToQueue'
        ],
        'pushTestThreeToQueue' => [
            'controller' => 'SampleController',
            'help'       => 'push TEST 3',
            'action'     => 'pushTestThreeToQueue'
        ],
        'processJobQueue' => [
            'controller' => 'SampleController',
            'help'       => 'Process Job Queue',
            'action'     => 'processJobQueue'
        ]
    ]
];

try {
    $app = new Pop\Application($config);
    $app->router()->addControllerParams(
        '*', [
            'application' => $app
        ]
    );
    $app->run();
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
```

**Comment by nicksagona** [comment]
So here are the details:
- I have a folder like you, called `data`
- If I run the individual commands, they all work as they should, like you mentioned.
- Here's the sequence of me pushing to the queue and then processing the queue, and the results (screenshots attached)

**Comment by nicksagona** [comment]
1. You can see the `data` folder is empty:

![Screenshot from 2021-02-02 22-14-56](https://user-images.githubusercontent.com/898670/106697361-339e8200-65a4-11eb-85bc-660d940b0913.png)

**Comment by nicksagona** [comment]
2. I run the command `./app pushTestTwoToQueue` and it creates the queue in `data`

![Screenshot from 2021-02-02 22-18-15](https://user-images.githubusercontent.com/898670/106697589-a3ad0800-65a4-11eb-892a-83b72f7f658f.png)

![Screenshot from 2021-02-02 22-18-41](https://user-images.githubusercontent.com/898670/106697597-a90a5280-65a4-11eb-962a-2cdb12280229.png)

**Comment by nicksagona** [comment]
3. Then I run the command `./app processJobQueue` and the worker job in the queue executes correctly, and there is now a file `test2.txt` in the data folder:

![Screenshot from 2021-02-02 22-19-21](https://user-images.githubusercontent.com/898670/106697645-cb9c6b80-65a4-11eb-9a2d-b8b00cb44d85.png)

![Screenshot from 2021-02-02 22-20-26](https://user-images.githubusercontent.com/898670/106697692-e242c280-65a4-11eb-9b53-9141b69412e3.png)

**Comment by nicksagona** [comment]
I did this with the `pushTestThreeToQueue` command by itself and it worked as it should. Then I cleared out the queue and pushed both jobs onto the queue and they both executed correctly.

So, at this time, it appears to be working as intended. So I don't know if it's an environment issue or something along those lines? (Just for an FYI, I'm on Ubuntu running PHP 7.4.3.) Are you on a Linux distro or Windows?

**Comment by marshmanGit** [comment]
I have toyed with this over and over and still struggling to figure this out.  
Everything works up to the point of ./app processJobQueue then I get a Segmentation fault (core dumped) likely due the infinite loop that I mentioned early in this process. 

php 7.4.9
popos (ubuntu distro)

I can't imagine that php 7.4.3 -> 7.4.9 would be the culprit. So, I will keep digging in and keep you posted on any findings.

No windows here...sucks!!!

**Comment by nicksagona** [comment]
lol @ the windows comment. Can you post a screen shot of the exact error message you're getting?

**Comment by marshmanGit** [comment]
This is interesting.
In Router.php  line 369, I updated to include an additional line of code.

$action       = $this->routeMatch->getAction();
// 20210203 mg  Adding this line allows the process to work
$action = null === $forceRoute ? $this->routeMatch->getAction() : $forceRoute;
$this->action = ((null === $action) && ($this->routeMatch->isDynamicRoute())) ? 'index' : $action;

THIS WORKS - FOR ME ANYWAYS!!!!  Go figure...

**Comment by nicksagona** [comment]
Well that's good that it works, but it may be a bandaid that could fail in other situations. Like I mentioned in my comment on 12/16, the "forceRoute" value and "action" value reference different things (the "calling route" string and the "action" method in the controller, respectively.) So that may work in situations when the "route" value and "action" value are the same, but may fail when they are different? I'm not sure, I'd have to play it with though.

**Comment by marshmanGit** [comment]
Yeah, I was wondering about the route=action (same/same[different]) scenario as well.  I will do some testing to see where it might break.

**Comment by marshmanGit** [comment]
It does break with different route and action.  But for now I'm good with that so long as I remember that tidbit.  As time permits I will keep digging.
Thanks for the help.
